repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace

      - id: requirements-txt-fixer
        name: Sort requirements.txt

      - id: debug-statements
        name: No illegal import or breakpoint calls

      - id: flake8
        name: Lint python files (for config, see .flake8)

      - id: check-merge-conflict
        name: Files should not have merge conflict strings

      - id: detect-private-key
        name: No private keys in source control

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.5.0
    hooks:
      - id: markdownlint
        name: Linting markdown files (for config, see .markdownlint.json)
