---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods

  - repo: local
    hooks:
      - id: pyproject.toml
        name: validate pyproject.toml
        language: system
        entry: poetry check
        files: 'pyproject\.toml'
        pass_filenames: false

      - id: isort
        name: isort
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        language: system
        entry: poetry run flake8
        types: [python]
