[tool.poetry]
name = "affinity-groups-slackbot"
version = "0.1.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiodns = "3.0.0"
aiohttp = "3.8.4"
async-timeout = "4.0.2"
attrs = "22.2.0"
cffi = "1.15.1"
chardet = "5.1.0"
click = "8.1.3"
idna = "2.8"
jinja2 = "3.1.2"
markupsafe = "2.1.2"
multidict = "4.5.2"
pycares = "4.3.0"
pycparser = "2.19"
slackclient = "2.9.4"
werkzeug = "2.2.3"
yarl = "1.8.2"
itsdangerous = "^2.1.2"
flask = "^2.2.3"



[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-flask = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
