jobs:
  lint_and_test_code:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:29ab89fdada1f85c5d8fb685a2c71660f0c5f60c
    steps:
    - checkout
    - run:
        command: pre-commit run --all-files
        name: Run pre-commit hooks on all files
    - run:
        command: pipenv sync --dev
        name: Install dev dependencies
    - run:
        command: pipenv run pytest
        name: Run Python tests
    - store_test_results:
        path: test-results
    - store_artifacts:
        destination: tr1
        path: test-results
version: 2.1
workflows:
  pipeline:
    jobs:
    - lint_and_test_code:
        context:
        - org-global
  version: 2.1
