name: Automate Building and Pushing Docker to AWS ECR

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md**"
    branches: [main]

jobs:
  validate:
    uses: trussworks/shared-actions/.github/workflows/aws-ecr.yml@main
    secrets: inherit
