name: Automate Building and Pushing Docker to AWS ECR

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md**"
    branches: [main]

jobs:
  validate:
    uses: trussworks/shared-actions/.github/workflows/aws-ecr.yml@bd419488477c202a2ee405f1488da037a6f2c0a9 #v0.1.0
    secrets: inherit
    with:
      aws-region: "us-west-2"
