name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  python_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Poetry Install
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # need to keep at v3.9 because that's the latest in AWS Lambda
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest
