name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  asdf_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Poetry Install
        uses: actions/setup-python@v4
      - run: poetry install

      - name: Run Tests
        run: poetry run pytest
